sudo: false
matrix:
  include:
  - os: osx
    osx_image: xcode8.1
    # See also: https://github.com/Homebrew/homebrew-core/issues/6949
  - os: linux
    language: python
    python: pypy-5.3.1
  - os: linux
    language: python
    python: 2.6
  - os: linux
    language: python
    python: 2.7
  - os: linux
    language: python
    python: 3.3
  - os: linux
    language: python
    python: 3.4
  - os: linux
    language: python
    python: 3.5
  - os: linux
    language: python
    python: 3.6
    env:
    - DEPLOY=true
install:
  |
  if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
    pip install --upgrade pip setuptools tox-travis docutils;
  elif [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
    brew tap drolando/homebrew-deadsnakes;
    brew install python33 python34 python35 python3 pypy
    pip install --upgrade pip setuptools
    pip install --user tox docutils;
  fi
script:
- tox -- -O --github-access-token="$GITHUB_ACCESS_TOKEN"
- '[[ "$TRAVIS_TAG" = "" ]] || [[ "$TRAVIS_TAG" = "$(python setup.py --version)" ]]'
- '[[ "$TRAVIS_TAG" = "" ]] || grep "Version $TRAVIS_TAG" README.rst'
- '[[ "$TRAVIS_TAG" = "" ]] || ! grep -i "to be released" README.rst'
- '[[ "$(rst2html5.py README.rst 2>&1 > /dev/null | wc -l)" = "0" ]]'
before_deploy:
- 'rm -rf build/ dist/ fzf-*.json iterfzf/fzf iterfzf/fzf.exe'
- python setup.py sdist
- 'echo >> setup.cfg'
- 'echo "[bundle_fzf]" >> setup.cfg'
- 'echo "github-access-token = $GITHUB_ACCESS_TOKEN" >> setup.cfg'
- python setup.py bundle_fzf -p linux   -a 386   bdist_wheel
- python setup.py bundle_fzf -p linux   -a amd64 bdist_wheel
- python setup.py bundle_fzf -p freebsd -a 386   bdist_wheel
- python setup.py bundle_fzf -p freebsd -a amd64 bdist_wheel
- python setup.py bundle_fzf -p openbsd -a 386   bdist_wheel
- python setup.py bundle_fzf -p openbsd -a amd64 bdist_wheel
- python setup.py bundle_fzf -p darwin  -a 386   bdist_wheel
- python setup.py bundle_fzf -p darwin  -a amd64 bdist_wheel
- python setup.py bundle_fzf -p windows -a 386   bdist_wheel
- python setup.py bundle_fzf -p windows -a amd64 bdist_wheel
- python setup.py bundle_fzf -p linux   -a arm5  bdist_wheel
- python setup.py bundle_fzf -p linux   -a arm6  bdist_wheel
- python setup.py bundle_fzf -p linux   -a arm7  bdist_wheel
- python setup.py bundle_fzf -p linux   -a arm8  bdist_wheel
deploy:
- provider: releases
  api_key: "$GITHUB_ACCESS_TOKEN"
  file_glob: true
  file: dist/iterfzf-*.*
  skip_cleanup: true
  on:
    condition: '"$DEPLOY" = "true"'
    tags: true
