name: test
on:
  pull_request: {}
  push:
    branches:
    - "*"

jobs:
  test:
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: |
          3.8
          3.9
          3.10
          3.11
          pypy3.10
    - uses: install-pinned/tox@9977353bc5a21c2a433f7ff4419a1d6ef036b4ba
    - run: |
        set -e
        if [[ "$RUNNER_DEBUG" = "1" ]]; then
          debug_options="--verbose"
        fi
        tox --exit-and-dump-after 60 $debug_options
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: AlexanderMelde/yapf-action@master
